#!/usr/bin/env sh

yabai -m config external_bar                    all:30:0

# global settings
yabai -m config mouse_follows_focus             off
yabai -m config focus_follows_mouse             off
yabai -m config window_placement                second_child
yabai -m config window_topmost                  off
yabai -m config window_shadow                   off
yabai -m config window_border                   on
yabai -m config window_border_placement         exterior
yabai -m config window_border_width             10
yabai -m config window_border_radius            10
yabai -m config active_window_border_color      0xB2EBDBB2
yabai -m config normal_window_border_color      0xB2282828
yabai -m config insert_window_border_color      0xB2EBDBB2
yabai -m config window_opacity                  off
yabai -m config split_ratio                     0.50
yabai -m config auto_balance                    on
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize

# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     10
yabai -m config bottom_padding                  10
yabai -m config left_padding                    10
yabai -m config right_padding                   10
yabai -m config window_gap                      10

yabai -m config window_topmost                  on
yabai -m config window_shadow                   float

# Space labels
yabai -m space 1 --label "Primary"
yabai -m space 2 --label "Terminal"
yabai -m space 3 --label "Editor"
yabai -m space 4 --label "Work"
yabai -m space 5 --label "Media"
yabai -m space 6 --label "Social"
yabai -m space 7 --label "Float"
yabai -m space 8 --label "Secondary"

# Space config
yabai -m config --space 8 layout float

# Unmanaged
yabai -m rule --add app="^System Preferences$"  manage=off border=off
yabai -m rule --add app="Harvest"               manage=off border=off
yabai -m rule --add app="Finder"                manage=off border=off
yabai -m rule --add app="Preview"               manage=off border=off
yabai -m rule --add app="Simulator"             manage=off border=off
yabai -m rule --add app="Archive Utility"       manage=off border=off
yabai -m rule --add title='.*Welcome*.|Checkout*.|.*Configurations|Choose*.|Import*.|.*Charges|Tip*.|Rename*.' manage=off

# Primary
yabai -m rule --add app="Firefox"               space=1
yabai -m rule --add app="Brave"                 space=1

yabai -m rule --add app="Alacritty"             space=2
yabai -m rule --add app="Simulator"             space=2
yabai -m rule --add app="Skim"                  space=2

#Code
yabai -m rule --add app="Android Studio"        space=3
yabai -m rule --add app="Code"    space=3

# Communication
yabai -m rule --add app="Microsoft Teams"       space=4
yabai -m rule --add app="Microsoft Outlook"     space=4

# Media
yabai -m rule --add app="Music"                 space=5
yabai -m rule --add app="QuickTime Player"      space=5
yabai -m rule --add app="VLC"                   space=5
yabai -m rule --add app="Spotify"               space=5

# Social
yabai -m rule --add app="Keybase"               space=6
yabai -m rule --add app="Signal"                space=6
yabai -m rule --add app="Simplenote"            space=6

# Tools
yabai -m rule --add app="Microsoft Word"        space=7
yabai -m rule --add app="Sequel Pro"            space=7
yabai -m rule --add app="Postman"               space=7
yabai -m rule --add app="Sourcetree"            space=7
yabai -m rule --add app="Activity Monitor"      space=7
yabai -m rule --add app="App Store"             space=7

# Floating
yabai -m rule --add app="^System Preferences$"  space=8
