#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar                    all:35:0

# global settings
yabai -m config mouse_follows_focus             off
yabai -m config focus_follows_mouse             off
yabai -m config window_placement                second_child
yabai -m config window_topmost                  off
yabai -m config window_shadow                   off
yabai -m config window_border                   on
yabai -m config window_border_placement         exterior
yabai -m config window_border_width             3
yabai -m config window_border_radius            3
yabai -m config active_window_border_color      0xB2EBDBB2
yabai -m config normal_window_border_color      0xB2282828
yabai -m config insert_window_border_color      0xB2EBDBB2
yabai -m config window_opacity                  off
yabai -m config split_ratio                     0.50
yabai -m config auto_balance                    on
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize

# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     10
yabai -m config bottom_padding                  10
yabai -m config left_padding                    10
yabai -m config right_padding                   10
yabai -m config window_gap                      10

yabai -m config window_topmost                  on
yabai -m config window_shadow                   float

# Space labels
yabai -m space 1 --label "Browser"
yabai -m space 2 --label "Terminal"
yabai -m space 3 --label "Editor"
yabai -m space 4 --label "Plan"
yabai -m space 5 --label "Private"
yabai -m space 6 --label "Work"
yabai -m space 7 --label "Media"
yabai -m space 8 --label "Tools"
yabai -m space 9 --label "Float"

# Space config
yabai -m config --space 8 layout float

# Unmanaged
yabai -m rule --add app="^System Preferences$"  manage=off border=off
yabai -m rule --add app="Harvest"               manage=off border=off
yabai -m rule --add app="Finder"                manage=off border=off
yabai -m rule --add app="Preview"               manage=off border=off
yabai -m rule --add app="Simulator"             manage=off border=off
yabai -m rule --add app="Archive Utility"       manage=off border=off
yabai -m rule --add app="Activity Monitor"      manage=off border=off
yabai -m rule --add title='.*Welcome*.|Checkout*.|.*Configurations|Choose*.|Import*.|.*Charges|Tip*.|Rename*.' manage=off

# Primary
yabai -m rule --add app="Firefox"               space=1
yabai -m rule --add app="Brave"                 space=1

# Terminal
yabai -m rule --add app="Alacritty"             space=2

#Code
yabai -m rule --add app="Android Studio"        space=3
yabai -m rule --add app="Code"                  space=3

#Code
yabai -m rule --add app="Calendar"              space=4
yabai -m rule --add app="Mail"                  space=4

# Private
yabai -m rule --add app="Keybase"               space=5
yabai -m rule --add app="Signal"                space=5
yabai -m rule --add app="Simplenote"            space=5

# Work
yabai -m rule --add app="Microsoft Teams"       space=6
yabai -m rule --add app="Slack"                 space=6
yabai -m rule --add app="Outlook"               space=6
yabai -m rule --add app="Skype for Business"    space=6


# Media
yabai -m rule --add app="Music"                 space=7
yabai -m rule --add app="QuickTime Player"      space=7
yabai -m rule --add app="VLC"                   space=7
yabai -m rule --add app="Spotify"               space=7

# Tools
yabai -m rule --add app="Microsoft Word"        space=8
yabai -m rule --add app="Sequel Pro"            space=8
yabai -m rule --add app="Studio 3T"             space=8
yabai -m rule --add app="Postman"               space=8
yabai -m rule --add app="App Store"             space=8
